CREATE TABLE IF NOT EXISTS office_bearers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  year VARCHAR(20),
  email VARCHAR(255),
  phone VARCHAR(50),
  bio TEXT,
  image_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 